### ISSUE TITLE
Please change the default branch 

### ISSUE THREAD

**Issue by amanjeev** [CanDIG/candig_tyk#10]
This repo is being listed in the `candig-server` [documents](https://candig-server.readthedocs.io/en/v1.3.0/development.html) and is a good candidate for change in the branch names. I am not sure what the new names should be but `master` definitely is not something we want to keep. Please help move this repo to a better branch nomenclature. 

@haoyuanli : leaving it to you since you are mulling over the branch names in our repos, per @ljdursi

**Comment by jimmyhli** [comment]
Thanks
